### ISSUE TITLE
First Try Review

### ISSUE THREAD

**Issue by theAkito** [dl-tg/scaffolder#11]
Greetings! :wave:

Thank you for this piece of software.

I'll summarise thoughts & issues I discovered, when using this project's product for the first time.

* Templating folder & file names.
    ```
    src:
      {nimpackage.nim}: |
        echo "yes"
    ```
* Accept configurations files named either `*.yaml` or `*.yml`.
* Make `--name` optional, if you want to scaffold into the current directory, rather than creating a new one.
* Optionally read variables from some `variables.yml` or something.
* Allow creating files without extensions by using something like `myfile.FILE` to create the file `myfile`.

You tell me, whether I should create separate issues or what we otherwise could do with these suggestions. 😄

**Comment by cemister** [comment]
@theAkito 

1) If you mean adding support for variables in file/folder names, then sure thing. TODO. Is that fine?
```
src:
   {file_name}: |
       ...
```
file_name can be set by adding the variables flag, --variables file_name:test.nim

2) I apologize but I don't think I understand it correctly. Both yaml and yml should work, and the asterisk shouldn't be a problem too.
3) TODO
4) I don't think we will implement that because there's really no reason to. We will add a way to set default value like `!MYVAR: 0` though.
5) TODO because it distinguishes it from folder names and prevents possible confusion.

Thank you very much for your feedback!

**Comment by theAkito** [comment]
> 2\. I apologize but I don't think I understand it correctly. Both yaml and yml should work, and the asterisk shouldn't be a problem too.

```nu
scaffold --name $"test_(date now | date format "%Y-%m-%dT%H:%M:%S")" --yaml ../configs/nim
Could not find ../configs/nim.yaml # Errors on `yml`, but not on `yaml`.
```

It specifically searches for a file with the `yaml` extensions, rather than supporting both.



> file_name can be set by adding the variables flag, --variables file_name:test.nim

This part is good, however...

> `{file_name}: |`

This is where I'm not sure about it. If we put it additional complexity in it.

According to this [answer](https://stackoverflow.com/a/21195482), braces should work in the file name, however, I'm not sure whether the majority of parsers are smart enough for that. Would not want a badly linted YAML in my code editor, every time I look at a valid scaffolder YAML file.

If that would be the case, one might also create an additional option.

```yaml
src:
   file_name: |
       ...
```

```
--pathname file_name:test/test.nim
```

This way, the keys would have no braces in it & yet, it'd be clear for scaffolder where to look for.

It's also possible to first use the existing `--variables` option for this, as you pointed out, but to keep it experimental, so it can be still changed, if issues on this topic gather in relevant amounts.

**Comment by cemister** [comment]
@theAkito Braces there are to distinguish it from normal text, it's like the dollar sign prefix in BASH. And if you want to set a variable to a path, wrapping the value in double quotes should do it, so the terminal doesn't get confused

However, there's an option which solves the problem without creating a completely new markup language.

We might differentiate it from normal yaml by changing the extension from .yaml to .scf.yaml, and then I can fork the YAML VSCode plugin to make it work with scaffolder yaml, and then tweak it for better linting, highlighting etc.

But, then I'd also have to do it at least for Sublime Text, IntelliJ IDEA (which I don't even possess). Those are the most popular variants, then there's also vim/nvim, emacs, Kate and so on.

It's always beneficial to abide by the languages conventions, but in context of Scaffolder, it means compromising functionality. 

As for yml, yes, I did hardcode it to search for yaml. It's only one letter difference and shouldn't be a problem unless working with a lot of them (in next update I still will add compatibility for yml, even though a simple bash command can change the file extensions quickly if working with big amount of *yml* files)

Perhaps, a Boolean flag like --yml to opt out for .yml would do it?

**Comment by cemister** [comment]
@theAkito P.S You should wrap variable references in double quotes if they're in folder/file names like `"{var}": ...` to avoid YAML syntax error. 1.1.8 was released and now it's supported. Optional --name will be coming together with default variable definitions, sorry for that - forgot to include them in this one.

**Comment by dl-tg** [comment]
@theAkito I have made name flag optional now
